# Generated by Django 5.2.4 on 2025-07-17 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schol', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='studant',
            new_name='student',
        ),
    ]
